// Here are the 100 most popular words in English, as totally
// stolen from here: https://gist.github.com/gravitymonkey/2406023

//took the liberty of removing any words that contained less than 3 characters //iperez

class words {
  constructor(word) {
    this.word = word
    var word = [
      "the",
      "and",
      "you",
      "that",
      "was",
      "for",
      "are",
      "with",
      "his",
      "they",
      "this",
      "have",
      "from",
      "one",
      "had",
      "word",
      "but",
      "not",
      "what",
      "all",
      "were",
      "when",
      "your",
      "can",
      "said",
      "there",
      "use",
      "each",
      "which",
      "she",
      "how",
      "their",
      "will",
      "other",
      "about",
      "out",
      "many",
      "then",
      "them",
      "these",
      "some",
      "her",
      "would",
      "make",
      "like",
      "him",
      "into",
      "time",
      "has",
      "look",
      "two",
      "more",
      "write",
      "see",
      "number",
      "way",
      "could",
      "people",
      "than",
      "first",
      "water",
      "been",
      "call",
      "who",
      "oil",
      "its",
      "now",
      "find",
      "long",
      "down",
      "day",
      "did",
      "get",
      "come",
      "made",
      "may",
      "part"
    ]
  }
}
